# Generated by Django 2.2.7 on 2020-01-31 19:50

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('number', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('floor', models.CharField(max_length=256)),
                ('capacity', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(4, 'Must not exceed 4 members')])),
            ],
        ),
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('student_ID', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('level', models.PositiveIntegerField()),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tenants', to='hotel.Room')),
            ],
        ),
    ]
